### PR TITLE
writing functions challenges 

### PR DESCRIPTION
**Pull request by jt14den**
first step is to clear out existing challenges, next will be working on adding more relevant challenges to the lesson.

### CODE REVIEW

**Comment by jt14den** [comment]
will be adding to this.

**Comment by chennesy** [comment]
@jt14den I added new exercises to the episode. I can't add you as a Reviewer since you submitted the PR, but if you have time to take a look and things look good, go ahead and Merge this one. thanks!

**Comment by chennesy** [comment]
Fixes #15

**Review by jt14den — COMMENTED** [review]
looks great. thanks!

**Pull request merged**
