### PR TITLE
Update libraries.md--standardizing libraries or packages

### PR DESCRIPTION
**Pull request by scottcpeterson**
Changed packages to libraries again for standardization.

### CODE REVIEW

**Review by chennesy — APPROVED** [review]
Thanks @scottcpeterson! 

In the future, can you please package together similar small changes to a single file like the updates you just made to libraries.md into a single PR? It would be easier to review one PR with all of the changes at once, instead of looking through multiple PRs.

**Comment by scottcpeterson** [comment]
Hi Cody,
I try to do that, but I broke this down into parts because in some places the changes were obvious, but others maybe weren't and I rewrote things a bit, and so Iwasn't sure if you would approve those. I didn't want to do a pull request where there was a combination of things that should be changed and things that wouldn't be changed.
Best,
Scott

**Comment by scottcpeterson** [comment]
And sometimes I will do a pull request for one thing and realize later in the episode there are more similar things like that. Sorry if it becomes a hassle.

**Comment by chennesy** [comment]
No big deal at all, and that makes sense. It is easier on the approver side though if changes to one file and on a related-theme (e.g., a bunch of copy-edits) are packaged into a single PR. Then whoever is reviewing/approving can edit the file as needed to accept some and reject other parts. But it makes it much easier to see what all is being changed and review at once.

Thanks again though! These were all helpful changes!

**Pull request merged**
